# .github/workflows/deploy.yml
name: Deploy to App Engine
on:
  push:
    branches:
      - main
  
jobs:
  deploy:
    name: Deploy to App Engine
    runs-on: ubuntu-latest
    
    steps:
    - name: 'Setup Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v0'
      with:
        project_id: '${{ env.PROJECT_ID }}'
        service_account_key: '${{ secrets.KEY_JSON }}'

    - name: 'Deploy to App Engine'
      run: 'gcloud app deploy app.yaml --promote --stop-previous-version --project sep6-350115'

    
