# .github/workflows/deploy.yml
name: Deploy to App Engine
on:
  push:
    branches:
      - main
env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  APP_ID: SEP6
  RUN_REGION: us-east1
  SA_KEY_JSON: ${{ secrets.KEY_JSON }}
  
jobs:
  deploy:
    name: Deploy to App Engine
    runs-on: ubuntu-latest
    
    steps:
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.KEY_JSON }}'

    - name: 'Deploy to App Engine'
      uses: 'google-github-actions/deploy-appengine@v0'
      with:
        promote: true
        version: 'v1'
